org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# /- should work now with Modstitch (and Stonecutter..?) 0.7+
org.gradle.configuration-cache=true

# Update Gradle wrapper with `./gradlew wrapper --gradle-version latest`

# Mod properties
mod.name=Better Minecraft
mod.id=betterminecraft
mod.group=de.shyyyuki
mod.version=1.0.0
mod.author=ShyyYuki
mod.desc=
mod.credits=
mod.license=
mod.source=ShyyYuki/betterminecraft
mod.curseforge=
mod.modrinth=

# Plugin versions
# /- https://maven.kikugie.dev/#/snapshots/dev/kikugie/fletching-table/fletching-table.mixin
plugin.fletching-table-catalog=0.2
# /- https://kotlinlang.org/docs/releases.html
plugin.kotlin=2.4.20
# /- https://github.com/isXander/modstitch-toolkit/tree/main#tools
plugin.mtk.manifests=0.1.5
# /- https://github.com/modmuss50/mod-publish-plugin?tab=readme-ov-file#basic-usage
plugin.mod-publish-plugin=2.2.0
# /- https://stonecutter.kikugie.dev/blog/changes/
plugin.stonecutter=0.9.7
# /- https://github.com/isxander/modstitch-stonecutter-template/blob/master/build.gradle.kts#L2
plugin.modstitch=0.8.5

# /- Fabric specific dependencies - https://fabricmc.net/develop
fabric.loom=1.18-SNAPSHOT
fabric.loader=0.19.5
# /- Neoforge specific dependencies
#neo.mod-dev-gradle=_
#neo.loader=20.2.93
# /- Legacy forge specific dependencies
#forge.mod-dev-gradle=_
#forge.loader=_

# Publishing metadata - phase is specified in the version (alpha | beta) and defaults to stable
loaders=fabric
targets=1.20.1,1.21.1,1.21.11,26.1.2,26.2,26.3,26.4
required=fabric-api,yacl
optionals=modmenu,no-chat-reports
# warns: "conflicts" <-> fabric, "discouraged" <-> neo [NOT supported on hosting sites]
# /- crashes: "breaks" <-> fabric, "incompatible" <-> neo [supported on hosting sites]
incompatibles=
embedded=